name: 🚀 Deploy RDS MySQL

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    name: Deploy RDS
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do Código
        uses: actions/checkout@v4

      - name: 🔑 Configurar Credenciais AWS
        run: |
          mkdir -p ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_session_token=${{ secrets.AWS_SESSION_TOKEN }}" >> ~/.aws/credentials
          echo "[default]" > ~/.aws/config
          echo "region=us-east-1" >> ~/.aws/config
          chmod 600 ~/.aws/credentials ~/.aws/config

      - name: 🏗️ Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: 🔄 Inicializar Terraform
        run: |
          cd terraform
          terraform init

      - name: ✅ Aplicar Terraform
        run: |
          cd terraform
          terraform apply -auto-approve
